name: teacher_planner
description: A teacher planning application with weekly schedules, term planning, and enhanced features.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  http: ^1.1.0
  file_picker: ^6.2.1
  share_plus: ^7.2.2
  table_calendar: ^3.1.3
  google_fonts: ^6.1.0
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.0.7
  pdf: ^3.10.7
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
